// <auto-generated />
using FizzBuzzGame.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FizzBuzzGame.API.Data.Migrations
{
    [DbContext(typeof(FizzBuzzGameContext))]
    [Migration("20250829040433_UpdateRuleModel")]
    partial class UpdateRuleModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("FizzBuzzGame.API.Models.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Divisor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Divisor = 5,
                            IsActive = true,
                            Text = "Buzz"
                        },
                        new
                        {
                            Id = 2,
                            Divisor = 3,
                            IsActive = false,
                            Text = "Fizz"
                        },
                        new
                        {
                            Id = 3,
                            Divisor = 15,
                            IsActive = false,
                            Text = "FizzBuzz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
